version: '3'

services:
  backend:
    image: sidney3i/af-backend:1
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  frontend:
    image: sidney3i/af-frontend:1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/dist
  nginx:
    image: sidney3i/af-nginx:1
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:
