version: '3'

services:
  backend:
    image: python:3.8-slim
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  frontend:
    image: node:alpine
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/dist
  nginx:
    image: nginx:1.19.0-alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:
