version: '3'

services:
  backend:
    image: sidney3i/af-backend:1
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - 8000:8000
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: always
  frontend:
    image: sidney3i/af-frontend:1
    volumes:
      - frontend:/app/dist
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: always
  nginx:
    image: sidney3i/af-nginx:2
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: always
volumes:
  static:
  frontend:
